
/**
* LibraryService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryServicesInterface.idl
* Wednesday, April 3, 2019 10:48:34 o'clock AM EDT
*/

public interface LibraryService extends LibraryServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryService
