
/**
* LibraryServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryServicesInterface.idl
* Friday, April 5, 2019 at 6:22:30 PM Eastern Daylight Time
*/

abstract public class LibraryServiceHelper
{
  private static String  _id = "IDL:LibraryService:1.0";

  public static void insert (org.omg.CORBA.Any a, LibraryService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LibraryService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LibraryServiceHelper.id (), "LibraryService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LibraryService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_LibraryServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LibraryService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LibraryService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibraryService)
      return (LibraryService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _LibraryServiceStub stub = new _LibraryServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LibraryService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LibraryService)
      return (LibraryService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _LibraryServiceStub stub = new _LibraryServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
