
/**
* LibraryService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryServicesInterface.idl
* Friday, April 5, 2019 at 4:56:18 PM Eastern Daylight Time
*/

public interface LibraryService extends LibraryServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryService
