
/**
* LibraryService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryServicesInterface.idl
* Monday, March 18, 2019 3:04:52 PM EDT
*/

public interface LibraryService extends LibraryServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryService
